version: '3'

services:
  trew-component-starter:
    container_name: trew-component-starter
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4001
    build:
      context: "."
    image: trew-component-starter:local
    ports:
      - 4001:4001
